services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: vaultpay
      POSTGRES_USER: vaultpay
      POSTGRES_PASSWORD: vaultpay_dev
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
