services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
      - "40000:40000"
    command:
      [
        "dlv",
        "debug",
        "./cmd/api",
        "--headless",
        "--listen=:40000",
        "--api-version=2",
        "--accept-multiclient",
        "--continue",
        "--build-flags=-buildvcs=false"
      ]

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: vaultpay
      POSTGRES_USER: vaultpay
      POSTGRES_PASSWORD: vaultpay_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaultpay -d vaultpay"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
