ARG GO_VERSION=1.25

FROM golang:${GO_VERSION}-bookworm

ARG DELVE_VERSION=v1.26.3

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@${DELVE_VERSION}

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080 40000
