services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      HTTP_ADDR: ":8080"
      DATABASE_URL: "postgres://vaultpay:vaultpay_dev@postgres:5432/vaultpay?sslmode=disable"
      RABBITMQ_URL: "amqp://vaultpay:vaultpay_dev@rabbitmq:5672/"
      RABBITMQ_DIAL_TIMEOUT: "5s"
      RABBITMQ_PUBLISH_TIMEOUT: "5s"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
      - "40000:40000"
    command:
      [
        "dlv",
        "debug",
        "./cmd/api",
        "--headless",
        "--listen=:40000",
        "--api-version=2",
        "--accept-multiclient",
        "--continue",
        "--build-flags=-buildvcs=false"
      ]

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: vaultpay
      POSTGRES_USER: vaultpay
      POSTGRES_PASSWORD: vaultpay_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaultpay -d vaultpay"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: vaultpay
      RABBITMQ_DEFAULT_PASS: vaultpay_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  pgdata:
  rabbitmqdata:
